[package]
name = "blah"
version = "0.1.0"
authors = ["George Kaplan <george@georgekaplan.xyz>"]
edition = "2018"

[dependencies]
warp = "0.1.15"
futures = "0.1"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
hyper = "0.12.27"
